AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 3.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
